name: Deploy
on: push

jobs:
    build:
        runs-on: ubuntu-latest

        #services:
        #    redis:
        #        image: redis
        #        ports:
        #            - 6379:6379

        steps:
            #- name: Install redis cli
            #  run: sudo apt-get update -y && sudo apt-get install redis-tools -y

            #- name: Test redis
            #  run: redis-cli -h localhost -p 6379 ping

            - name: Print variable
              run: echo "${{ secrets.TOKEN_SECRET_C3_GH_ACTIONS }}"

            - name: Checkout
              uses: actions/checkout@v4 # Clona el repositorio

            - name: Setup
              uses: actions/setup-node@v4
              with:
                node-version: '22'

            - name: Instalar dependencias
              run: npm install

            - name: Correr Tests
              run: npm run test

            - name: Build page
              run: npm run build

            - name: Upload static files as artifact (Uso de Action de Marketplace)
              uses: actions/upload-pages-artifact@v3 
              with:
                path: public/ # ruta del archivo dist (build)

    deploy:
        #if: ${{ always() }} # Debe funcionar sí o sí, así el job anterior caiga en error
        runs-on: ubuntu-latest
        needs: build

        environment:
            name: github-pages
            url: ${{ steps.deployment-pages.outputs.page_url }}

        steps:
            - name: Deploy to GitHub Pages (Uso de Action de Marketplace)
              id: deployment-pages
              uses: actions/deploy-pages@v4
